// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gycehrjelmcvvjrutbsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5Y2VocmplbG1jdnZqcnV0YnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTE1MjIsImV4cCI6MjA2Mzc2NzUyMn0.zEFxDEuDkcKzDAgN4rHDDL0Wy3mA-9EPSibtGqHGyVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);